const { mungedLocationData } = require('../lib/Utils/munge.js');
const { mungedWeatherData } = require('../lib/Utils/munge.js');

require('dotenv').config();


  describe('munge functions', () => {

    test('takes in location data and returns targeted data', async() => {

      const expectation = 
        {
          "formatted_query": "Seattle, King County, Washington, USA",
          "latitude": "47.6038321",
          "longitude": "-122.3300624"
        };

      const locationInput = [
          {
              "place_id": "235549103",
              "licence": "https://locationiq.com/attribution",
              "osm_type": "relation",
              "osm_id": "237385",
              "boundingbox": [
                  "47.4810022",
                  "47.7341357",
                  "-122.459696",
                  "-122.224433"
              ],
              "lat": "47.6038321",
              "lon": "-122.3300624",
              "display_name": "Seattle, King County, Washington, USA",
              "class": "place",
              "type": "city",
              "importance": 0.772979173564379,
              "icon": "https://locationiq.org/static/images/mapicons/poi_place_city.p.20.png"
          },
          {
              "place_id": "55417079",
              "licence": "https://locationiq.com/attribution",
              "osm_type": "node",
              "osm_id": "4836954932",
              "boundingbox": [
                  "20.7199184",
                  "20.7200184",
                  "-103.3763786",
                  "-103.3762786"
              ],
              "lat": "20.7199684",
              "lon": "-103.3763286",
              "display_name": "Seattle, Villas de Guadalupe, Zapopan, Jalisco, 38901, Mexico",
              "class": "place",
              "type": "neighbourhood",
              "importance": 0.30000000000000004
          },
          {
              "place_id": "156976950",
              "licence": "https://locationiq.com/attribution",
              "osm_type": "way",
              "osm_id": "291707810",
              "boundingbox": [
                  "25.1837689",
                  "25.1845505",
                  "121.4465868",
                  "121.4474398"
              ],
              "lat": "25.18415975",
              "lon": "121.446939985985",
              "display_name": "Seattle, Lanweibu, Beitou Village, Danhai, Tamsui District, New Taipei, Taiwan",
              "class": "landuse",
              "type": "residential",
              "importance": 0.30000000000000004
          },
          {
              "place_id": "84138175",
              "licence": "https://locationiq.com/attribution",
              "osm_type": "way",
              "osm_id": "10671266",
              "boundingbox": [
                  "41.9611659",
                  "41.9657274",
                  "-121.9226362",
                  "-121.9226043"
              ],
              "lat": "41.9641881",
              "lon": "-121.922629",
              "display_name": "Seattle, Dorris, Siskiyou County, California, 96058, USA",
              "class": "highway",
              "type": "residential",
              "importance": 0.2
          },
          {
              "place_id": "90129562",
              "licence": "https://locationiq.com/attribution",
              "osm_type": "way",
              "osm_id": "22919051",
              "boundingbox": [
                  "14.6180684",
                  "14.6213139",
                  "121.0429669",
                  "121.0448923"
              ],
              "lat": "14.6195488",
              "lon": "121.0440164",
              "display_name": "Seattle, Kaunlaran, Cubao, 4th District, Quezon City, Eastern Manila District, Metro Manila, 1111, Philippines",
              "class": "highway",
              "type": "residential",
              "importance": 0.2
          },
          {
              "place_id": "160325077",
              "licence": "https://locationiq.com/attribution",
              "osm_type": "way",
              "osm_id": "307770120",
              "boundingbox": [
                  "28.8472264",
                  "28.8487875",
                  "-111.9789493",
                  "-111.9780146"
              ],
              "lat": "28.8481394",
              "lon": "-111.9783605",
              "display_name": "Seattle, Nuevo Kino, Bahía Kino, Hermosillo, Sonora, Mexico",
              "class": "highway",
              "type": "residential",
              "importance": 0.2
          },
          {
              "place_id": "95155603",
              "licence": "https://locationiq.com/attribution",
              "osm_type": "way",
              "osm_id": "29546551",
              "boundingbox": [
                  "14.4191845",
                  "14.4193677",
                  "120.9180883",
                  "120.9187908"
              ],
              "lat": "14.4192428",
              "lon": "120.918312",
              "display_name": "Seattle, ACM Woodstock Homes Ph9, Alapan 1-A, Bayan Luma VI, Imus, Cavite, Calabarzon, 4103, Philippines",
              "class": "highway",
              "type": "residential",
              "importance": 0.2
          },
          {
              "place_id": "203034631",
              "licence": "https://locationiq.com/attribution",
              "osm_type": "way",
              "osm_id": "561843639",
              "boundingbox": [
                  "47.4112544",
                  "47.4112745",
                  "-122.2621269",
                  "-122.2608738"
              ],
              "lat": "47.4112602",
              "lon": "-122.260923",
              "display_name": "Seattle, Kent, King County, Washington, 98032, USA",
              "class": "highway",
              "type": "service",
              "importance": 0.175
          },
          {
              "place_id": "312432792",
              "licence": "https://locationiq.com/attribution",
              "osm_type": "way",
              "osm_id": "165271257",
              "boundingbox": [
                  "14.6696649",
                  "14.6703081",
                  "121.0988688",
                  "121.0994135"
              ],
              "lat": "14.6703081",
              "lon": "121.0994135",
              "display_name": "Seattle, Vista Real Classica, Batasan Hills, 2nd District, Quezon City, Eastern Manila District, Metro Manila, 1808, Philippines",
              "class": "highway",
              "type": "service",
              "importance": 0.175
          },
          {
              "place_id": "6534059",
              "licence": "https://locationiq.com/attribution",
              "osm_type": "node",
              "osm_id": "668442224",
              "boundingbox": [
                  "47.6028456",
                  "47.6029456",
                  "-122.3398908",
                  "-122.3397908"
              ],
              "lat": "47.6028956",
              "lon": "-122.3398408",
              "display_name": "Seattle, Colman Dock, West Edge, Belltown, Seattle, King County, Washington, 98104, USA",
              "class": "amenity",
              "type": "ferry_terminal",
              "importance": 0.101
          }
      
      ]

      const actual = mungedLocationData(locationInput)

      expect(actual).toEqual(expectation);
    });

    test('takes in weather data and returns targeted data', async() => {

        const expectation = [
                {forecast: "Overcast clouds", time: "Thursday, July 01, 2021"},    
                { forecast: 'Overcast clouds', time: 'Thursday, July 1, 2021' },
                { forecast: 'Scattered clouds', time: 'Friday, July 2, 2021' },
                { forecast: 'Clear Sky', time: 'Saturday, July 3, 2021' },
                { forecast: 'Broken clouds', time: 'Sunday, July 4, 2021' },
                { forecast: 'Scattered clouds', time: 'Monday, July 5, 2021' },
                { forecast: 'Clear Sky', time: 'Tuesday, July 6, 2021' },
                { forecast: 'Clear Sky', time: 'Wednesday, July 7, 2021' },
                { forecast: 'Few clouds', time: 'Thursday, July 8, 2021' },
                { forecast: 'Broken clouds', time: 'Friday, July 9, 2021' },
                { forecast: 'Clear Sky', time: 'Saturday, July 10, 2021' },
                { forecast: 'Clear Sky', time: 'Sunday, July 11, 2021' },
                { forecast: 'Clear Sky', time: 'Monday, July 12, 2021' },
                { forecast: 'Clear Sky', time: 'Tuesday, July 13, 2021' },
                { forecast: 'Clear Sky', time: 'Wednesday, July 14, 2021' },
                { forecast: 'Broken clouds', time: 'Thursday, July 15, 2021' },
                { forecast: 'Broken clouds', time: 'Friday, July 16, 2021' },
        ]
        const weatherInput = {
            "data": [
                {
                    "moonrise_ts": 1625126740,
                    "wind_cdir": "SSE",
                    "rh": 72,
                    "pres": 1009.52,
                    "high_temp": 21.6,
                    "sunset_ts": 1625199059,
                    "ozone": 316.198,
                    "moon_phase": 0.402977,
                    "wind_gust_spd": 6.89844,
                    "snow_depth": 0,
                    "clouds": 70,
                    "ts": 1625122860,
                    "sunrise_ts": 1625141802,
                    "app_min_temp": 17.9,
                    "wind_spd": 1.15338,
                    "pop": 10,
                    "wind_cdir_full": "south-southeast",
                    "slp": 1014.21,
                    "moon_phase_lunation": 0.73,
                    "valid_date": "2021-07-01",
                    "app_max_temp": 21.5,
                    "vis": 23.671,
                    "dewpt": 14.5,
                    "snow": 0,
                    "uv": 5.35685,
                    "weather": {
                        "icon": "c04d",
                        "code": 804,
                        "description": "Overcast clouds"
                    },
                    "wind_dir": 155,
                    "max_dhi": null,
                    "clouds_hi": 3,
                    "precip": 0.3125,
                    "low_temp": 17.3,
                    "max_temp": 21.8,
                    "moonset_ts": 1625174184,
                    "datetime": "2021-07-01",
                    "temp": 19.8,
                    "min_temp": 17.8,
                    "clouds_mid": 0,
                    "clouds_low": 70
                },
                {
                    "moonrise_ts": 1625214179,
                    "wind_cdir": "NNE",
                    "rh": 66,
                    "pres": 1010.08,
                    "high_temp": 25.1,
                    "sunset_ts": 1625285442,
                    "ozone": 317.135,
                    "moon_phase": 0.307585,
                    "wind_gust_spd": 4.29688,
                    "snow_depth": 0,
                    "clouds": 36,
                    "ts": 1625209260,
                    "sunrise_ts": 1625228239,
                    "app_min_temp": 16.8,
                    "wind_spd": 1.89974,
                    "pop": 0,
                    "wind_cdir_full": "north-northeast",
                    "slp": 1014.75,
                    "moon_phase_lunation": 0.76,
                    "valid_date": "2021-07-02",
                    "app_max_temp": 25,
                    "vis": 24.096,
                    "dewpt": 13.9,
                    "snow": 0,
                    "uv": 8.19013,
                    "weather": {
                        "icon": "c02d",
                        "code": 802,
                        "description": "Scattered clouds"
                    },
                    "wind_dir": 30,
                    "max_dhi": null,
                    "clouds_hi": 0,
                    "precip": 0,
                    "low_temp": 15.5,
                    "max_temp": 25.1,
                    "moonset_ts": 1625264487,
                    "datetime": "2021-07-02",
                    "temp": 21,
                    "min_temp": 16.7,
                    "clouds_mid": 0,
                    "clouds_low": 36
                },
                {
                    "moonrise_ts": 1625301621,
                    "wind_cdir": "SW",
                    "rh": 54,
                    "pres": 1002.75,
                    "high_temp": 31.5,
                    "sunset_ts": 1625371823,
                    "ozone": 309.646,
                    "moon_phase": 0.220519,
                    "wind_gust_spd": 5.30078,
                    "snow_depth": 0,
                    "clouds": 0,
                    "ts": 1625295660,
                    "sunrise_ts": 1625314679,
                    "app_min_temp": 14.7,
                    "wind_spd": 1.99915,
                    "pop": 0,
                    "wind_cdir_full": "southwest",
                    "slp": 1013.38,
                    "moon_phase_lunation": 0.8,
                    "valid_date": "2021-07-03",
                    "app_max_temp": 30.1,
                    "vis": 24.128,
                    "dewpt": 11.6,
                    "snow": 0,
                    "uv": 9.10726,
                    "weather": {
                        "icon": "c01d",
                        "code": 800,
                        "description": "Clear Sky"
                    },
                    "wind_dir": 215,
                    "max_dhi": null,
                    "clouds_hi": 0,
                    "precip": 0,
                    "low_temp": 13.1,
                    "max_temp": 31.6,
                    "moonset_ts": 1625354797,
                    "datetime": "2021-07-03",
                    "temp": 22.6,
                    "min_temp": 14.5,
                    "clouds_mid": 0,
                    "clouds_low": 0
                },
                {
                    "moonrise_ts": 1625389135,
                    "wind_cdir": "SW",
                    "rh": 57,
                    "pres": 1004.1,
                    "high_temp": 29.7,
                    "sunset_ts": 1625458201,
                    "ozone": 310.708,
                    "moon_phase": 0.144393,
                    "wind_gust_spd": 5.60156,
                    "snow_depth": 0,
                    "clouds": 62,
                    "ts": 1625382060,
                    "sunrise_ts": 1625401121,
                    "app_min_temp": 13.1,
                    "wind_spd": 2.49318,
                    "pop": 0,
                    "wind_cdir_full": "southwest",
                    "slp": 1014.77,
                    "moon_phase_lunation": 0.83,
                    "valid_date": "2021-07-04",
                    "app_max_temp": 28.4,
                    "vis": 23.6633,
                    "dewpt": 10.7,
                    "snow": 0,
                    "uv": 8.11352,
                    "weather": {
                        "icon": "c03d",
                        "code": 803,
                        "description": "Broken clouds"
                    },
                    "wind_dir": 214,
                    "max_dhi": null,
                    "clouds_hi": 59,
                    "precip": 0,
                    "low_temp": 13.2,
                    "max_temp": 29.8,
                    "moonset_ts": 1625445124,
                    "datetime": "2021-07-04",
                    "temp": 20.8,
                    "min_temp": 13,
                    "clouds_mid": 5,
                    "clouds_low": 4
                },
                {
                    "moonrise_ts": 1625476800,
                    "wind_cdir": "SSW",
                    "rh": 56,
                    "pres": 1005.81,
                    "high_temp": 30.9,
                    "sunset_ts": 1625544576,
                    "ozone": 313.219,
                    "moon_phase": 0.144393,
                    "wind_gust_spd": 5.89844,
                    "snow_depth": 0,
                    "clouds": 32,
                    "ts": 1625468460,
                    "sunrise_ts": 1625487565,
                    "app_min_temp": 13.2,
                    "wind_spd": 2.14048,
                    "pop": 0,
                    "wind_cdir_full": "south-southwest",
                    "slp": 1016.5,
                    "moon_phase_lunation": 0.86,
                    "valid_date": "2021-07-05",
                    "app_max_temp": 29.4,
                    "vis": 23.9633,
                    "dewpt": 10.6,
                    "snow": 0,
                    "uv": 7.41607,
                    "weather": {
                        "icon": "c02d",
                        "code": 802,
                        "description": "Scattered clouds"
                    },
                    "wind_dir": 207,
                    "max_dhi": null,
                    "clouds_hi": 28,
                    "precip": 0,
                    "low_temp": 13.8,
                    "max_temp": 31,
                    "moonset_ts": 1625531524,
                    "datetime": "2021-07-05",
                    "temp": 21,
                    "min_temp": 13,
                    "clouds_mid": 5,
                    "clouds_low": 5
                },
                {
                    "moonrise_ts": 1625564704,
                    "wind_cdir": "ESE",
                    "rh": 49,
                    "pres": 1004.12,
                    "high_temp": 33,
                    "sunset_ts": 1625630949,
                    "ozone": 307.031,
                    "moon_phase": 0.0818814,
                    "wind_gust_spd": 5.91016,
                    "snow_depth": 0,
                    "clouds": 0,
                    "ts": 1625554860,
                    "sunrise_ts": 1625574011,
                    "app_min_temp": 13.8,
                    "wind_spd": 2.03602,
                    "pop": 0,
                    "wind_cdir_full": "east-southeast",
                    "slp": 1014.88,
                    "moon_phase_lunation": 0.9,
                    "valid_date": "2021-07-06",
                    "app_max_temp": 28.5,
                    "vis": 24.128,
                    "dewpt": 9.5,
                    "snow": 0,
                    "uv": 8.8113,
                    "weather": {
                        "icon": "c01d",
                        "code": 800,
                        "description": "Clear Sky"
                    },
                    "wind_dir": 110,
                    "max_dhi": null,
                    "clouds_hi": 0,
                    "precip": 0,
                    "low_temp": 14.6,
                    "max_temp": 30.5,
                    "moonset_ts": 1625621821,
                    "datetime": "2021-07-06",
                    "temp": 21.8,
                    "min_temp": 13.6,
                    "clouds_mid": 0,
                    "clouds_low": 0
                },
                {
                    "moonrise_ts": 1625652960,
                    "wind_cdir": "SW",
                    "rh": 47,
                    "pres": 1001.12,
                    "high_temp": 31.5,
                    "sunset_ts": 1625717319,
                    "ozone": 302.625,
                    "moon_phase": 0.0356518,
                    "wind_gust_spd": 4.13281,
                    "snow_depth": 0,
                    "clouds": 0,
                    "ts": 1625641260,
                    "sunrise_ts": 1625660458,
                    "app_min_temp": 14.6,
                    "wind_spd": 1.57312,
                    "pop": 0,
                    "wind_cdir_full": "southwest",
                    "slp": 1011.62,
                    "moon_phase_lunation": 0.93,
                    "valid_date": "2021-07-07",
                    "app_max_temp": 31.2,
                    "vis": 24.128,
                    "dewpt": 10.1,
                    "snow": 0,
                    "uv": 8.80962,
                    "weather": {
                        "icon": "c01d",
                        "code": 800,
                        "description": "Clear Sky"
                    },
                    "wind_dir": 228,
                    "max_dhi": null,
                    "clouds_hi": 0,
                    "precip": 0,
                    "low_temp": 13.8,
                    "max_temp": 33.4,
                    "moonset_ts": 1625711978,
                    "datetime": "2021-07-07",
                    "temp": 23.6,
                    "min_temp": 14.4,
                    "clouds_mid": 0,
                    "clouds_low": 0
                },
                {
                    "moonrise_ts": 1625741684,
                    "wind_cdir": "WSW",
                    "rh": 48,
                    "pres": 1000.5,
                    "high_temp": 25.5,
                    "sunset_ts": 1625803687,
                    "ozone": 304.406,
                    "moon_phase": 0.00810085,
                    "wind_gust_spd": 4.30469,
                    "snow_depth": 0,
                    "clouds": 1,
                    "ts": 1625727660,
                    "sunrise_ts": 1625746908,
                    "app_min_temp": 13.8,
                    "wind_spd": 2.134,
                    "pop": 0,
                    "wind_cdir_full": "west-southwest",
                    "slp": 1011.06,
                    "moon_phase_lunation": 0.96,
                    "valid_date": "2021-07-08",
                    "app_max_temp": 29.5,
                    "vis": 23.836,
                    "dewpt": 8.8,
                    "snow": 0,
                    "uv": 8.63832,
                    "weather": {
                        "icon": "c02d",
                        "code": 801,
                        "description": "Few clouds"
                    },
                    "wind_dir": 238,
                    "max_dhi": null,
                    "clouds_hi": 1,
                    "precip": 0,
                    "low_temp": 13.7,
                    "max_temp": 31.8,
                    "moonset_ts": 1625801834,
                    "datetime": "2021-07-08",
                    "temp": 21.9,
                    "min_temp": 13.5,
                    "clouds_mid": 0,
                    "clouds_low": 0
                },
                {
                    "moonrise_ts": 1625830967,
                    "wind_cdir": "SSW",
                    "rh": 61,
                    "pres": 1007.75,
                    "high_temp": 27,
                    "sunset_ts": 1625890052,
                    "ozone": 330.875,
                    "moon_phase": 0.00101022,
                    "wind_gust_spd": 7.51172,
                    "snow_depth": 0,
                    "clouds": 45,
                    "ts": 1625814060,
                    "sunrise_ts": 1625833359,
                    "app_min_temp": 13.7,
                    "wind_spd": 3.13811,
                    "pop": 0,
                    "wind_cdir_full": "south-southwest",
                    "slp": 1018.56,
                    "moon_phase_lunation": 1,
                    "valid_date": "2021-07-09",
                    "app_max_temp": 25,
                    "vis": 24.128,
                    "dewpt": 9.7,
                    "snow": 0,
                    "uv": 7.64783,
                    "weather": {
                        "icon": "c03d",
                        "code": 803,
                        "description": "Broken clouds"
                    },
                    "wind_dir": 197,
                    "max_dhi": null,
                    "clouds_hi": 5,
                    "precip": 0,
                    "low_temp": 12,
                    "max_temp": 25.5,
                    "moonset_ts": 1625891247,
                    "datetime": "2021-07-09",
                    "temp": 18,
                    "min_temp": 13.1,
                    "clouds_mid": 12,
                    "clouds_low": 38
                },
                {
                    "moonrise_ts": 1625920819,
                    "wind_cdir": "SSW",
                    "rh": 54,
                    "pres": 1011.12,
                    "high_temp": 25.3,
                    "sunset_ts": 1625976415,
                    "ozone": 318.562,
                    "moon_phase": 0.0153056,
                    "wind_gust_spd": 5.01953,
                    "snow_depth": 0,
                    "clouds": 0,
                    "ts": 1625900460,
                    "sunrise_ts": 1625919812,
                    "app_min_temp": 12,
                    "wind_spd": 2.2891,
                    "pop": 0,
                    "wind_cdir_full": "south-southwest",
                    "slp": 1021.88,
                    "moon_phase_lunation": 0.03,
                    "valid_date": "2021-07-10",
                    "app_max_temp": 26.4,
                    "vis": 24.128,
                    "dewpt": 8.8,
                    "snow": 0,
                    "uv": 8.72366,
                    "weather": {
                        "icon": "c01d",
                        "code": 800,
                        "description": "Clear Sky"
                    },
                    "wind_dir": 199,
                    "max_dhi": null,
                    "clouds_hi": 0,
                    "precip": 0,
                    "low_temp": 15.1,
                    "max_temp": 27.6,
                    "moonset_ts": 1625980156,
                    "datetime": "2021-07-10",
                    "temp": 19.6,
                    "min_temp": 11.8,
                    "clouds_mid": 0,
                    "clouds_low": 0
                },
                {
                    "moonrise_ts": 1626011138,
                    "wind_cdir": "N",
                    "rh": 49,
                    "pres": 1010.25,
                    "high_temp": 22,
                    "sunset_ts": 1626062775,
                    "ozone": 298.625,
                    "moon_phase": 0.0509948,
                    "wind_gust_spd": 6.82812,
                    "snow_depth": 0,
                    "clouds": 0,
                    "ts": 1625986860,
                    "sunrise_ts": 1626006266,
                    "app_min_temp": 17.3,
                    "wind_spd": 1.95533,
                    "pop": 0,
                    "wind_cdir_full": "north",
                    "slp": 1021,
                    "moon_phase_lunation": 0.07,
                    "valid_date": "2021-07-11",
                    "app_max_temp": 24.8,
                    "vis": 24.128,
                    "dewpt": 9.5,
                    "snow": 0,
                    "uv": 6.81931,
                    "weather": {
                        "icon": "c01d",
                        "code": 800,
                        "description": "Clear Sky"
                    },
                    "wind_dir": 11,
                    "max_dhi": null,
                    "clouds_hi": 0,
                    "precip": 0,
                    "low_temp": 17.8,
                    "max_temp": 28.8,
                    "moonset_ts": 1626068599,
                    "datetime": "2021-07-11",
                    "temp": 21.3,
                    "min_temp": 13.8,
                    "clouds_mid": 0,
                    "clouds_low": 0
                },
                {
                    "moonrise_ts": 1626101754,
                    "wind_cdir": "S",
                    "rh": 51,
                    "pres": 1006.25,
                    "high_temp": 19.1,
                    "sunset_ts": 1626149133,
                    "ozone": 310.625,
                    "moon_phase": 0.107207,
                    "wind_gust_spd": 4.01172,
                    "snow_depth": 0,
                    "clouds": 0,
                    "ts": 1626073260,
                    "sunrise_ts": 1626092722,
                    "app_min_temp": 15.1,
                    "wind_spd": 1.34862,
                    "pop": 0,
                    "wind_cdir_full": "south",
                    "slp": 1016.75,
                    "moon_phase_lunation": 0.1,
                    "valid_date": "2021-07-12",
                    "app_max_temp": 24.6,
                    "vis": 24.128,
                    "dewpt": 9.3,
                    "snow": 0,
                    "uv": 6.76848,
                    "weather": {
                        "icon": "c01d",
                        "code": 800,
                        "description": "Clear Sky"
                    },
                    "wind_dir": 186,
                    "max_dhi": null,
                    "clouds_hi": 0,
                    "precip": 0,
                    "low_temp": 18.3,
                    "max_temp": 28.5,
                    "moonset_ts": 1626156673,
                    "datetime": "2021-07-12",
                    "temp": 20,
                    "min_temp": 11.8,
                    "clouds_mid": 0,
                    "clouds_low": 0
                },
                {
                    "moonrise_ts": 1626192512,
                    "wind_cdir": "SE",
                    "rh": 51,
                    "pres": 1003,
                    "high_temp": 21.6,
                    "sunset_ts": 1626235488,
                    "ozone": 317.25,
                    "moon_phase": 0.182227,
                    "wind_gust_spd": 2.40039,
                    "snow_depth": 0,
                    "clouds": 0,
                    "ts": 1626159660,
                    "sunrise_ts": 1626179179,
                    "app_min_temp": 17.4,
                    "wind_spd": 1.21509,
                    "pop": 0,
                    "wind_cdir_full": "southeast",
                    "slp": 1014,
                    "moon_phase_lunation": 0.13,
                    "valid_date": "2021-07-13",
                    "app_max_temp": 22,
                    "vis": 24.128,
                    "dewpt": 9.5,
                    "snow": 0,
                    "uv": 6.71145,
                    "weather": {
                        "icon": "c01d",
                        "code": 800,
                        "description": "Clear Sky"
                    },
                    "wind_dir": 137,
                    "max_dhi": null,
                    "clouds_hi": 0,
                    "precip": 0,
                    "low_temp": 12.8,
                    "max_temp": 28.8,
                    "moonset_ts": 1626244488,
                    "datetime": "2021-07-13",
                    "temp": 20,
                    "min_temp": 12.8,
                    "clouds_mid": 0,
                    "clouds_low": 0
                },
                {
                    "moonrise_ts": 1626283322,
                    "wind_cdir": "SW",
                    "rh": 53,
                    "pres": 1005.25,
                    "high_temp": 29.9,
                    "sunset_ts": 1626321841,
                    "ozone": 306.875,
                    "moon_phase": 0.273495,
                    "wind_gust_spd": 3.11523,
                    "snow_depth": 0,
                    "clouds": 0,
                    "ts": 1626246060,
                    "sunrise_ts": 1626265638,
                    "app_min_temp": 17.8,
                    "wind_spd": 2.1027,
                    "pop": 0,
                    "wind_cdir_full": "southwest",
                    "slp": 1015.75,
                    "moon_phase_lunation": 0.17,
                    "valid_date": "2021-07-14",
                    "app_max_temp": 21,
                    "vis": 24.128,
                    "dewpt": 9.8,
                    "snow": 0,
                    "uv": 6.72107,
                    "weather": {
                        "icon": "c01d",
                        "code": 800,
                        "description": "Clear Sky"
                    },
                    "wind_dir": 216,
                    "max_dhi": null,
                    "clouds_hi": 0,
                    "precip": 0,
                    "low_temp": 12.2,
                    "max_temp": 29.9,
                    "moonset_ts": 1626332147,
                    "datetime": "2021-07-14",
                    "temp": 19.7,
                    "min_temp": 12.2,
                    "clouds_mid": 0,
                    "clouds_low": 0
                },
                {
                    "moonrise_ts": 1626374167,
                    "wind_cdir": "ESE",
                    "rh": 50,
                    "pres": 1004,
                    "high_temp": 30,
                    "sunset_ts": 1626408192,
                    "ozone": 326.125,
                    "moon_phase": 0.377541,
                    "wind_gust_spd": 2.61133,
                    "snow_depth": 0,
                    "clouds": 50,
                    "ts": 1626332460,
                    "sunrise_ts": 1626352099,
                    "app_min_temp": 18.3,
                    "wind_spd": 1.9034,
                    "pop": 0,
                    "wind_cdir_full": "east-southeast",
                    "slp": 1014.5,
                    "moon_phase_lunation": 0.2,
                    "valid_date": "2021-07-15",
                    "app_max_temp": 21.4,
                    "vis": 24.128,
                    "dewpt": 9.2,
                    "snow": 0,
                    "uv": 6.6714,
                    "weather": {
                        "icon": "c03d",
                        "code": 803,
                        "description": "Broken clouds"
                    },
                    "wind_dir": 121,
                    "max_dhi": null,
                    "clouds_hi": 46,
                    "precip": 0,
                    "low_temp": 13.3,
                    "max_temp": 30,
                    "moonset_ts": 1626333340,
                    "datetime": "2021-07-15",
                    "temp": 20.2,
                    "min_temp": 13.3,
                    "clouds_mid": 50,
                    "clouds_low": 0
                },
                {
                    "moonrise_ts": 1626465076,
                    "wind_cdir": "S",
                    "rh": 72,
                    "pres": 1005,
                    "high_temp": 20.5,
                    "sunset_ts": 1626494540,
                    "ozone": 348.375,
                    "moon_phase": 0.489906,
                    "wind_gust_spd": 6.01953,
                    "snow_depth": 0,
                    "clouds": 40,
                    "ts": 1626418860,
                    "sunrise_ts": 1626438560,
                    "app_min_temp": 15.3,
                    "wind_spd": 2.63113,
                    "pop": 40,
                    "wind_cdir_full": "south",
                    "slp": 1015.5,
                    "moon_phase_lunation": 0.24,
                    "valid_date": "2021-07-16",
                    "app_max_temp": 18.5,
                    "vis": 24.128,
                    "dewpt": 11.8,
                    "snow": 0,
                    "uv": 2.92287,
                    "weather": {
                        "icon": "c03d",
                        "code": 803,
                        "description": "Broken clouds"
                    },
                    "wind_dir": 183,
                    "max_dhi": null,
                    "clouds_hi": 2,
                    "precip": 1.8125,
                    "low_temp": 15.3,
                    "max_temp": 20.5,
                    "moonset_ts": 1626420953,
                    "datetime": "2021-07-16",
                    "temp": 17.2,
                    "min_temp": 15.3,
                    "clouds_mid": 1,
                    "clouds_low": 40
                }
            ],
            "city_name": "Seattle",
            "lon": "-122.33207",
            "timezone": "America/Los_Angeles",
            "lat": "47.60621",
            "country_code": "US",
            "state_code": "WA"
        }
  
  
  
  
        const actual = mungedWeatherData(weatherInput)
  
        expect(actual.length).toBeGreaterThan(0)
        expect(actual[0]).toHaveProperty('forecast')
        expect(actual[0]).toHaveProperty('time')
      });


  });
